apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentx.fullname" . }}
type: Opaque
stringData:
  AGENTX_DB_URL: {{ include "agentx.pgUrl" . | quote }}
  AGENTX_TELEMETRY_URL: {{ include "agentx.chUrl" . | quote }}
